name: Auto Compile LaTeX
on:
  push:
    branches: [ main ]  # 或是你的主要分支名稱 (可能是 master)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # 指向你指定的檔案路徑
          root_file: Courses_Teaching/L1_Intro/L1_Intro_data_2026_v1.tex
          compiler: xelatex
          args: "-pdf -interaction=nonstopmode -halt-on-error"

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Courses_Teaching/L1_Intro/ # 只發布這個資料夾下的結果
          publish_branch: gh-pages
