      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # 這裡去掉前面的 Courses_Teaching/
          root_file: L1_Intro/L1_Intro_data_2026_v1.tex
          compiler: xelatex
          args: "-pdf -interaction=nonstopmode -halt-on-error"

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 這裡也去掉前面的 Courses_Teaching/
          publish_dir: ./L1_Intro/ 
          publish_branch: gh-pages
